//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoManager.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MotoManager.Application.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entregador não encontrado..
        /// </summary>
        public static string DELIVERYRIDER_NOT_FOUND {
            get {
                return ResourceManager.GetString("DELIVERYRIDER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O entregador foi cadastrado com sucesso..
        /// </summary>
        public static string DELIVERYRIDER_UPDATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("DELIVERYRIDER_UPDATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error registering motorcycle..
        /// </summary>
        public static string ERROR_REGISTERING_MOTOCYCLE {
            get {
                return ResourceManager.GetString("ERROR_REGISTERING_MOTOCYCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Field {0} is required..
        /// </summary>
        public static string FIELD_REQUIRED {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados inválidos.
        /// </summary>
        public static string INVALID_DATA {
            get {
                return ResourceManager.GetString("INVALID_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo {0} informado é inválido..
        /// </summary>
        public static string INVALID_FIELD {
            get {
                return ResourceManager.GetString("INVALID_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid license plate..
        /// </summary>
        public static string INVALID_PLATE {
            get {
                return ResourceManager.GetString("INVALID_PLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Request mal formada.
        /// </summary>
        public static string INVALID_REQUEST_MESSAGE {
            get {
                return ResourceManager.GetString("INVALID_REQUEST_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Motorcycle already registered..
        /// </summary>
        public static string MOTOCYCLE_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("MOTOCYCLE_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Moto não encontrada.
        /// </summary>
        public static string MOTOCYCLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MOTOCYCLE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Motocycle registered succesfully.
        /// </summary>
        public static string MOTOCYCLE_REGISTERED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MOTOCYCLE_REGISTERED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Moto removida com sucesso..
        /// </summary>
        public static string MOTORCYCLE_REMOVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MOTORCYCLE_REMOVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validation failed for one or more fields..
        /// </summary>
        public static string MULTI_FIELDS_ERROS {
            get {
                return ResourceManager.GetString("MULTI_FIELDS_ERROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Placa modificada com sucesso.
        /// </summary>
        public static string PLATE_UPDATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("PLATE_UPDATED_SUCCESSFULLY", resourceCulture);
            }
        }
    }
}
